#!/usr/bin/env python3
"""Build and verify a site's "Featured on" badge block from a launch ledger.

Usage:
  scripts/badges.py render  launches/<p>/listings.yaml --format html|jsx  > featured-on.(html|tsx)
  scripts/badges.py verify  launches/<p>/listings.yaml [--url https://site]

render: emits every collected badge snippet exactly as the platform gave it (href/src untouched),
        either as plain HTML or as a JSX component (class→className, style→object, void tags closed).
        Paste/replace the generated block in one commit, deploy once per batch.
verify: fetches the live page (server-rendered HTML, like the platforms' crawlers) and checks that
        every badge link is present and obeys its platform rule; exits 1 if any required badge is missing.
"""
import re, sys, html, urllib.request
import yaml

def load(path):
    d = yaml.safe_load(open(path))
    items = [l for l in d.get('listings') or [] if (l.get('badge') or {}).get('html') and l.get('status') != 'skipped']
    return d, items

def to_jsx(snippet):
    s = snippet.strip()
    s = re.sub(r'\sclass=', ' className=', s)
    s = re.sub(r'\sfor=', ' htmlFor=', s)
    def style(m):
        props = []
        for decl in m.group(1).split(';'):
            if ':' not in decl:
                continue
            k, v = decl.split(':', 1)
            k = re.sub(r'-([a-z])', lambda x: x.group(1).upper(), k.strip())
            props.append(f'{k}: {v.strip()!r}'.replace("'", '"'))
        return ' style={{ ' + ', '.join(props) + ' }}'
    s = re.sub(r'\sstyle="([^"]*)"', style, s)
    s = re.sub(r'<(img|br|source|input)([^>]*?)\s*/?>', r'<\1\2 />', s)
    s = re.sub(r'\s(\w+)\s*=\s*"', r' \1="', s)          # normalize `height = "54px"`
    s = s.replace('<img', '{/* eslint-disable-next-line @next/next/no-img-element */}\n<img', 1) if '<img' in s else s
    return s

def render(path, fmt):
    d, items = load(path)
    if fmt == 'html':
        print('<!-- Featured on — generated by launch-in-all-platforms; links must stay server-rendered -->')
        print('<div class="featured-on">')
        for l in items:
            print(f"  <!-- {l['platform']} -->\n  {l['badge']['html'].strip()}")
        print('</div>')
        return
    print('// Featured on — generated by launch-in-all-platforms/scripts/badges.py.')
    print('// Server Component on purpose: directory crawlers check the HTML the server sends.')
    print('// Keep each href and src exactly as the directory gave it.')
    print('export function FeaturedOn() {\n  return (\n    <div className="featured-on">')
    for l in items:
        body = to_jsx(l['badge']['html']).replace('\n', '\n      ')
        print(f"      {{/* {l['platform']} */}}\n      {body}")
    print('    </div>\n  );\n}')

def verify(path, url=None):
    d, items = load(path)
    url = url or d.get('site')
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 launch-in-all-platforms'})
    page = urllib.request.urlopen(req, timeout=30).read().decode('utf-8', 'replace')
    anchors = re.findall(r'<a\b[^>]*>', page, re.I)
    missing = 0
    for l in items:
        b = l['badge']
        href = html.unescape(re.search(r'href="([^"]+)"', b['html']).group(1))
        tag = next((a for a in anchors if html.unescape(re.search(r'href="([^"]*)"', a).group(1) if re.search(r'href="([^"]*)"', a) else '') == href), None)
        problems = []
        if not tag:
            problems.append('NOT FOUND')
        else:
            rule = (b.get('rules') or '').lower()
            rel = re.search(r'rel="([^"]*)"', tag)
            if 'no rel' in rule and rel:
                problems.append(f'has rel="{rel.group(1)}" but platform requires none')
            if rel and re.search(r'nofollow|sponsored|ugc', rel.group(1)):
                problems.append(f'rel="{rel.group(1)}" makes the backlink worthless to the platform check')
            if 'ref=badge' in rule and 'ref=badge' not in href:
                problems.append('missing ?ref=badge')
        level = 'ERROR' if problems and b.get('required', True) else ('WARN ' if problems else 'OK   ')
        if level == 'ERROR':
            missing += 1
        print(f"{level} {l['platform']:<18} {href}  {'; '.join(problems)}")
    print(f'\n{len(items)} badges checked on {url}, {missing} required badge problem(s)')
    sys.exit(1 if missing else 0)

if __name__ == '__main__':
    a = sys.argv[1:]
    if len(a) < 2 or a[0] not in ('render', 'verify'):
        sys.exit(__doc__)
    if a[0] == 'render':
        render(a[1], a[a.index('--format') + 1] if '--format' in a else 'jsx')
    else:
        verify(a[1], a[a.index('--url') + 1] if '--url' in a else None)
